server.port=8080
spring.datasource.url=jdbc:mariadb://a1ad851bd6fa229d27c2b7bd579812fb1eccfb540bc3e52de553f41abfac6ba7:3306/student_db
spring.datasource.username=root
spring.datasource.password=redhat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
